#!/bin/bash


python3 handle_labels_multiple_query.py alihandikel reddit stackoverflow Informative
python3 handle_labels_multiple_query.py averneus reddit stackoverflow Informative
python3 handle_labels_multiple_query.py averneus neuvoo glassdoor linkedin JobApp
python3 handle_labels_multiple_query.py alihandikel neuvoo glassdoor linkedin JobApp
python3 handle_labels_multiple_query.py averneus dailycodingproblem DailyCode
python3 handle_labels_multiple_query.py averneus pythonweekly elementalselenium jsw@peterc Notes
